// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARKBVfnlAWuGVBMR5x6qDw7PTJVKD7Mbo',
    appId: '1:543445107634:web:f99d115c69d65ad9499aab',
    messagingSenderId: '543445107634',
    projectId: 'cronowork-1d33b',
    authDomain: 'cronowork-1d33b.firebaseapp.com',
    storageBucket: 'cronowork-1d33b.firebasestorage.app',
    measurementId: 'G-0YB3L9M21C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHinfehSlak7ODjiA4lbtFL3b7laRsz-4',
    appId: '1:543445107634:android:e6aeaee8f3e80b9e499aab',
    messagingSenderId: '543445107634',
    projectId: 'cronowork-1d33b',
    storageBucket: 'cronowork-1d33b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARKBVfnlAWuGVBMR5x6qDw7PTJVKD7Mbo',
    appId: '1:543445107634:web:de800e3e94d4613d499aab',
    messagingSenderId: '543445107634',
    projectId: 'cronowork-1d33b',
    authDomain: 'cronowork-1d33b.firebaseapp.com',
    storageBucket: 'cronowork-1d33b.firebasestorage.app',
    measurementId: 'G-43ESW58BM0',
  );

}